#!/bin/bash

# Load rvm
source ~/.bash_profile

if ! (command -v rvm || command -v mise) &> /dev/null; then
	echo "RVM or mise required for pfe"
	exit 1
fi

# Go to the pfe directory
pfe_root=$(dirname "${0}")
cd "${pfe_root}"

if ! command -v bundle &> /dev/null; then
	echo "Loading bundler and gems"
	gem install bundler
	bundle
fi

ruby pfe.rb ${@}